/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InfoImport } from './routes/info'
import { Route as HelloImport } from './routes/hello'

// Create/Update Routes

const InfoRoute = InfoImport.update({
  path: '/info',
  getParentRoute: () => rootRoute,
} as any)

const HelloRoute = HelloImport.update({
  path: '/hello',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hello': {
      preLoaderRoute: typeof HelloImport
      parentRoute: typeof rootRoute
    }
    '/info': {
      preLoaderRoute: typeof InfoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([HelloRoute, InfoRoute])

/* prettier-ignore-end */
